#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Feb 26 08:14:21 GMT+09:00 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
